# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          YT_KEY: ${{ secrets.YT_KEY }}
        run: |
          pip install pandas
          python csv_gen.py
          git config --global user.email "alokmatta@gmail.com"
          git config --global user.name "Alok"
          git add .
          git commit -m "Updating video.csv"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
